[build]
  command = "npm install && npm run build"
  publish = ".next"
  base = "."

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://iamsarath.netlify.app"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 